name: flutter_sound_lite
version: 2.0.3
description: Flutter plugin that relates to sound like audio and recorder.
#author: dooboolab<dooboolab@gmail.com>
homepage: https://github.com/dooboolab/flutter_sound

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"


dependencies:
  path_provider: ^2.0.2
#  logger: ^1.0.0
#  intl: ^0.17.0

#  recase: ^3.0.0
#  uuid: ^2.2.0
  provider: ^5.0.0
#  flutter_spinkit: ^4.0.0
  path: ">=1.0.0 <2.0.0"
#  synchronized: ^2.2.0


  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  #pedantic: ^1.9.0
  effective_dart: ^1.0.0
  #lint: ^1.1.1



flutter:
  plugin:
    platforms:
      android:
        package: com.dooboolab.fluttersound
        pluginClass: Flauto
      ios:
        pluginClass: Flauto
